/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FilmSubmission = IDL.Record({
  'submitterName' : IDL.Text,
  'country' : IDL.Text,
  'filmTitle' : IDL.Text,
  'submittedAt' : Time,
  'description' : IDL.Text,
  'director' : IDL.Text,
  'videoBlob' : IDL.Opt(ExternalBlob),
  'contactEmail' : IDL.Text,
  'ageGroup' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'commenterName' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'filmId' : IDL.Text,
});
export const Rating = IDL.Record({
  'createdAt' : IDL.Int,
  'stars' : IDL.Nat,
  'filmId' : IDL.Text,
  'raterName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addRating' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(FilmSubmission)], ['query']),
  'getAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getRatings' : IDL.Func([IDL.Text], [IDL.Vec(Rating)], ['query']),
  'submitFilm' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FilmSubmission = IDL.Record({
    'submitterName' : IDL.Text,
    'country' : IDL.Text,
    'filmTitle' : IDL.Text,
    'submittedAt' : Time,
    'description' : IDL.Text,
    'director' : IDL.Text,
    'videoBlob' : IDL.Opt(ExternalBlob),
    'contactEmail' : IDL.Text,
    'ageGroup' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'commenterName' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'filmId' : IDL.Text,
  });
  const Rating = IDL.Record({
    'createdAt' : IDL.Int,
    'stars' : IDL.Nat,
    'filmId' : IDL.Text,
    'raterName' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addRating' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(FilmSubmission)], ['query']),
    'getAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getRatings' : IDL.Func([IDL.Text], [IDL.Vec(Rating)], ['query']),
    'submitFilm' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };